name: MCWorldBorder
version: 1.0.0
main: com.dungewar.worldborder.WorldBorderPlugin
api-version: '1.21'
authors: [dungewar]
description: Randomly changes the world border over time and reports updates.
